### PR TITLE
Interactive/pixel play

### PR DESCRIPTION
**Pull request by andybelltree**
Was using size of canvas rather than size of image as cache. Also
turned off animation.

### CODE REVIEW

**Comment by haydenjackson01** [comment]
Was this meant to be a pull request into the uccser repo instead?

**Comment by andybelltree** [comment]
Ah woops. Yes it was...

**Comment by andybelltree** [comment]
I see Jack's created one to the correct repo :) Sorry about that!

**Comment by haydenjackson01** [comment]
All good I see it is also actually under the folder `pixel-viewer` where I was hunting for `pixel-play`.

**Pull request closed without merging**
